foreach(file gamecontrollerdb.txt soh.o2r)
    set(found "")
    foreach(dir "${BINARY_DIR}/soh" "${BINARY_DIR}" "${SOURCE_DIR}")
        if(EXISTS "${dir}/${file}" AND NOT found)
            file(SIZE "${dir}/${file}" size)
            if(size GREATER 0)
                set(found "${dir}/${file}")
            endif()
        endif()
    endforeach()
    if(found)
        file(COPY "${found}" DESTINATION "${BUNDLE}")
    elseif(file STREQUAL "soh.o2r")
        message(WARNING "iOS bundle: soh.o2r is missing; build the GenerateSohOtr "
                        "target or the app will exit on launch")
    else()
        message(WARNING "iOS bundle: ${file} is missing; controller mappings may be incomplete")
    endif()
endforeach()

file(REMOVE "${BUNDLE}/oot.o2r" "${BUNDLE}/oot-mq.o2r")
file(REMOVE_RECURSE "${BUNDLE}/mods")

set(archive_oot.o2r "${BUNDLE_ROM}")
set(archive_oot-mq.o2r "${BUNDLE_MQ_ROM}")
foreach(name oot.o2r oot-mq.o2r)
    set(archive "${archive_${name}}")
    if(NOT archive)
        continue()
    endif()
    if(NOT EXISTS "${archive}")
        message(FATAL_ERROR "No ROM archive at ${archive}")
    endif()
    set(probe "${BINARY_DIR}/bundle-rom-probe")
    file(REMOVE_RECURSE "${probe}")
    file(ARCHIVE_EXTRACT INPUT "${archive}" DESTINATION "${probe}" PATTERNS portVersion)
    set(major "")
    if(EXISTS "${probe}/portVersion")
        file(READ "${probe}/portVersion" bytes HEX LIMIT 3)
        string(SUBSTRING "${bytes}" 0 2 endian)
        string(SUBSTRING "${bytes}" 2 2 first)
        string(SUBSTRING "${bytes}" 4 2 second)
        if(endian STREQUAL "01")
            math(EXPR major "0x${first}${second}")
        else()
            math(EXPR major "0x${second}${first}")
        endif()
    endif()
    file(REMOVE_RECURSE "${probe}")
    if(NOT major STREQUAL VERSION_MAJOR)
        message(FATAL_ERROR "${archive} has port version major '${major}', this build is ${VERSION_MAJOR}. "
                            "Extract ${name} with the in-app extractor of this version.")
    endif()
    file(COPY_FILE "${archive}" "${BUNDLE}/${name}")
endforeach()

if(BUNDLE_MODS)
    file(GLOB_RECURSE mods RELATIVE "${BUNDLE_MODS}" "${BUNDLE_MODS}/*.o2r")
    foreach(mod ${mods})
        get_filename_component(dir "${BUNDLE}/mods/${mod}" DIRECTORY)
        file(COPY "${BUNDLE_MODS}/${mod}" DESTINATION "${dir}")
    endforeach()
endif()
