foreach(file gamecontrollerdb.txt soh.o2r)
    set(found "")
    foreach(dir "${BINARY_DIR}/soh" "${BINARY_DIR}" "${SOURCE_DIR}")
        if(EXISTS "${dir}/${file}" AND NOT found)
            file(SIZE "${dir}/${file}" size)
            if(size GREATER 0)
                set(found "${dir}/${file}")
            endif()
        endif()
    endforeach()
    if(found)
        file(COPY "${found}" DESTINATION "${BUNDLE}")
    elseif(file STREQUAL "soh.o2r")
        message(WARNING "iOS bundle: soh.o2r is missing; build the GenerateSohOtr "
                        "target or the app will exit on launch")
    else()
        message(WARNING "iOS bundle: ${file} is missing; controller mappings may be incomplete")
    endif()
endforeach()
